### PR TITLE
add OfficeBrainz logos

### PR DESCRIPTION
**Pull request by caroline-gschwend**
Add OfficeBrainz logos with and without text. (The vectors are transparent)
screen shot 2017-02-13 at 5 26 44 pm
screen shot 2017-02-13 at 5 26 53 pm

### CODE REVIEW

**Comment by MonkeyDo** [comment]
The spacing between the logo and the text isn't quite right.
It should be equivalent to the width of the lowercase letter r in "Brainz"

**Comment by caroline-gschwend** [comment]
Thanks for noticing @MonkeyDo ! I'll fix it

**Comment by MonkeyDo** [comment]
That makes me happy :)

I think you'll also need to vectorize the font, as it appears in default serif font for me in the browser:
capture d ecran 2017-02-14 a 16 18 01

**Comment by caroline-gschwend** [comment]
@MonkeyDo , does it look better now?

**Comment by MonkeyDo** [comment]
Yep!
capture d ecran 2017-02-14 a 16 30 06

**Review by mayhem — APPROVED** [review]
Woo!

**Pull request merged**
